### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by petroav**
Update README.

### CODE REVIEW

**Comment by petroav** [comment]
@sanjay990, please have a look when you get a chance.

**Comment by sanjay990** [comment]
I didn't see the comment stating tpch connector cannot be deleted.

**Comment by petroav** [comment]
You're right it's not in the docs. I wrote it as a comment in the code :)
https://github.com/prestodb/ambari-presto-service/blob/master/package/scripts/presto_coordinator.py#L92

I'll put up another commit in a bit, saying that the TPCH connector cannot be removed.

**Comment by sanjay990** [comment]
lgtm

**Pull request closed without merging**
