### PR TITLE
Update RPM and CLI links to 0.196

### PR DESCRIPTION
**Pull request by cavemandaveman**
Presto 0.190 works well with HDP/Ambari 2.6. This updates to the latest Presto and edits refs to new versions. Also assumes an update of this service to 1.3. 

I have a 1.3 release in my fork if you would like to test.

### CODE REVIEW

**Comment by teamsoo** [comment]
Cool! we're also testing 0.190 as well.

**Comment by mattsfuller** [comment]
Can you squash commit "Missed more hardcoded versions" with "Update RPM and CLI to 0.190" so it's cleaner. And then also rebase this branch on master. I fixed the issue why the build was failing. 

Once you do those two things the checks should pass and I'll merge to master and cut a release.

**Comment by cavemandaveman** [comment]
@mattsfuller Looks like 0.194 is the latest. Want me to change to this version as well? Or just get this merged in and then create a separate PR?

**Comment by mattsfuller** [comment]
hi @cavemandaveman, sure it would be best to update to the latest as well.

**Comment by cavemandaveman** [comment]
@mattsfuller I decided to rebase and redo the changes; seemed easier than squashing out of order commits as well as adding more commits on top of that. Please look it over again and let me know if you think it's good.

**Review by mattsfuller — APPROVED** [review]
approved

**Pull request merged**
